=head1 Time::Stamp

  use Time::Stamp 'gmstamp'; # default format is ISO 8601 / RFC 3339 / W3CDTF
  $stamp = gmstamp();
  $stamp = gmstamp($seconds);
  # default $stamp looks like '2010-08-05T12:13:14Z'
  # format can be changed with options on import

This module makes it easy to include timestamp functions
that are simple, easily readable, and fast.
For simple timestamps perl's built-in functions are all you need:
L<time|perlfunc/time>,
L<gmtime|perlfunc/gmtime> (or L<localtime|perlfunc/localtime>),
and L<sprintf|perlfunc/sprintf>...

See module POD for more information.

=head1 COPYRIGHT AND LICENSE

This software is copyright (c) 2011 by Randy Stauner.

This is free software; you can redistribute it and/or modify it under
the same terms as the Perl 5 programming language system itself.

=cut
